package plausibcheck.adress
//package，这个跟Java中的包名是差不多的
import com.neo.drools.model.Address;
import com.neo.drools.model.fact.AddressCheckResult;

rule "Postcode should be filled with exactly 5 numbers"
    when
    //Rule的LHS由条件元素（Conditional Elements—CE）和匹配模式（Patterns）组成
    
    	//Address(postcode != null, postcode matches "([0-9]{5})")有文本字段约束的Pattern
        address : Address(postcode != null, postcode matches "([0-9]{5})")
        checkResult : AddressCheckResult();
        
        
    //then，当when下面的表达式为true是then下方的代码才会执行，在这里可以直接编写Java代码（代码所需要的类通过import引入），当然也可以使用when模块定义的一些变量
    then
        checkResult.setPostCodeResult(true);
        checkResult.setNum(checkResult.getNum()+1);
		System.out.println("规则中打印日志：校验通过!");
		
//end 代表规则结束。
end




rule "xs gz"
    when
        address : Address(postcode != null, postcode.length ==5)
        checkResult : AddressCheckResult();
        
    then
        checkResult.setPostCodeResult(true);
        checkResult.setNum(checkResult.getNum()+1);
		System.out.println("规则x校验通过!");
end